env:
  es6: true
  browser: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  linebreak-style:
    - error
    - windows
  quotes:
    - warn
    - single
