env:
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
